name: mon-os-ublue
description: Mon image Fedora
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 43

modules:
  - type: rpm-ostree
    remove:
      - gnome-tour
      - firefox
      - firefox-langpacks
      - gnome-system-monitor
      - toolbox
      - htop
      - nvtop
      - yelp
    install:
      - fastfetch
      - distrobox
      - firewall-config
      - steam-devices
      - papirus-icon-theme

  - type: default-flatpaks
    configurations:
      - scope: system
        install:
          # === Applications GNOME ===
          - org.gnome.Calculator
          - org.gnome.Calendar
          - org.gnome.Characters
          - org.gnome.clocks
          - org.gnome.Logs
          - org.gnome.Maps
          - org.gnome.Weather
          - org.gnome.baobab
          - org.gnome.Papers
          
          # === Outils système ===
          - io.missioncenter.MissionCenter
          - it.mijorus.gearleve
          - io.github.flattool.Warehouse
          - io.github.flattool.Ignition
          - com.mattjakeman.ExtensionManager
          - com.github.tchx84.Flatseal
          - io.github.ilya_zlobintsev.LACT

          # === Theme ===
          - org.gtk.Gtk3theme.adw-gtk3-dark
          - org.gtk.Gtk3theme.adw-gtk3

          # === Virtualisation ===
          - com.ranfdev.DistroShelf
          - org.gnome.Boxes
          
          # === Applications ===
          - org.signal.Signal
          - org.remmina.Remmina
          - org.raspberrypi.rpi-imager
          - org.onlyoffice.desktopeditors
          - org.gnome.Lollypop
          - org.gnome.Evolution
          - org.gimp.GIMP
          - org.freecad.FreeCAD
          - org.deluge_torrent.deluge
          - net.cozic.joplin_desktop
          - me.proton.Mail
          - io.gitlab.news_flash.NewsFlash
          - io.gitlab.librewolf-community
          - im.riot.Riot
          - com.visualstudio.code
          - com.ultimaker.cura
          - com.spotify.Client
          - com.jeffser.Alpaca
          - com.jeffser.Alpaca.Plugins.AMD
          - com.jeffser.Alpaca.Plugins.Ollama
          - com.google.Chrome
          - com.discordapp.Discord
          - com.bitwarden.desktop

          # === Gaming ===
          - com.valvesoftware.Steam
          - com.heroicgameslauncher.hgl
          - com.vysp3r.ProtonPlus
          - io.github.benjamimgois.goverlay

  - type: brew
    auto-update: true        
    update-interval: '6h'     
    auto-upgrade: true       
    upgrade-interval: '1d'     
    brew-analytics: false

  - type: signing
